let games = [
  {
    title: "Cyberpunk 2077",
    cover: "assets/img/cover/cyberpunk-2077.jpg",
    developer: "CD Projekt Red",
    releaseYear: 2020,
    price: 29.99,
    platforms: [
      { name: "PC", icon: "assets/img/plattforms/pc.png" },
      { name: "PlayStation 5", icon: "assets/img/plattforms/ps5.png" },
      { name: "Xbox Series X/S", icon: "assets/img/plattforms/xboxseries.png" },
      { name: "Nintendo Switch", icon: "assets/img/plattforms/switch.png" },
    ],
    soldCopies: 25000000,
    genre: "Action-RPG",
    rating: 8.5,
    metacritic: 86,
    likes: 1234,
    ageRating: { name: "USK 18", icon: "assets/img/usk/usk-18.png" },
    modes: ["Singleplayer"],
    dlcs: ["Phantom Liberty"],
    tags: ["Open World", "Dystopie", "Story-driven", "First Person"],
    liked: true,
    description:
      "Tauche ein in die düstere Zukunft von Night City – einer offenen Welt voller Korruption, Machtkämpfe und kybernetischer Upgrades.",
    ownComment: [
      {
        name: "MyProfil",
        comment:
          "MAIN KOMMENTAR den ich loschen moechte wenn ich auch den eimer klicke",
        rating: 9,
        date: "2025-06-27",
      },
    ],
    comments: [
      {
        name: "PlayerOne",
        comment:
          "Nach den Patches ein Meisterwerk! Atmosphäre, Quests, Welt – alles top.",
        rating: 9,
        date: "2024-08-10",
      },
      {
        name: "NightCityFan",
        comment:
          "Keanu Reeves in einem Videospiel? Instant Buy! Dazu geile Musik & Design.",
        rating: 10,
        date: "2023-11-22",
      },
      {
        name: "BugHunter42",
        comment: "Zum Release unspielbar, aber heute wirklich lohnenswert.",
        rating: 7,
        date: "2022-03-01",
      },
    ],
    ingamePics: [
      "assets/img/ingame-pics/cyberpunk-2077/cyberpunk2077-1.png",
      "assets/img/ingame-pics/cyberpunk-2077/cyberpunk2077-2.png",
      "assets/img/ingame-pics/cyberpunk-2077/cyberpunk2077-3.png",
      "assets/img/ingame-pics/cyberpunk-2077/cyberpunk2077-4.png",
      "assets/img/ingame-pics/cyberpunk-2077/cyberpunk2077-5.png",
      "assets/img/ingame-pics/cyberpunk-2077/cyberpunk2077-6.png",
    ],
  },
  {
    title: "The Witcher 3: Wild Hunt",
    cover: "assets/img/cover/the-witcher-3.jpg",
    developer: "CD Projekt Red",
    releaseYear: 2015,
    price: 19.99,
    platforms: [
      { name: "PC", icon: "assets/img/plattforms/pc.png" },
      { name: "PS4", icon: "assets/img/plattforms/ps4.png" },
      { name: "PS5", icon: "assets/img/plattforms/ps5.png" },
      { name: "Xbox One", icon: "assets/img/plattforms/xboxone.png" },
      { name: "Xbox Series X/S", icon: "assets/img/plattforms/xboxseries.png" },
      { name: "Nintendo Switch", icon: "assets/img/plattforms/switch.png" },
    ],
    soldCopies: 50000000,
    genre: "Fantasy RPG",
    rating: 9.6,
    metacritic: 93,
    likes: 1234,
    ageRating: { name: "USK 18", icon: "assets/img/usk/usk-18.png" },
    modes: ["Singleplayer"],
    dlcs: ["Hearts of Stone", "Blood and Wine"],
    tags: ["Open World", "Story-driven", "Entscheidungen", "Magie"],
    liked: true,
    description:
      "Begleite Geralt von Riva durch eine dunkle Fantasywelt voller Monster, Intrigen und tragischer Schicksale.",
    ownComment: [],
    comments: [
      {
        name: "YenneferLover",
        comment:
          "Ein Meisterwerk. Die Nebenquests haben mehr Tiefe als andere Hauptstories.",
        rating: 10,
        date: "2023-06-15",
      },
    ],
    ingamePics: [
      "assets/img/ingame-pics/the-witcher-3/thewitcher3-1.png",
      "assets/img/ingame-pics/the-witcher-3/thewitcher3-2.png",
      "assets/img/ingame-pics/the-witcher-3/thewitcher3-3.png",
      "assets/img/ingame-pics/the-witcher-3/thewitcher3-4.png",
      "assets/img/ingame-pics/the-witcher-3/thewitcher3-5.png",
      "assets/img/ingame-pics/the-witcher-3/thewitcher3-6.png",
    ],
  },
  {
    title: "NBA 2K24",
    cover: "assets/img/cover/nba-2K24.jpg",
    developer: "Visual Concepts",
    releaseYear: 2023,
    price: 69.99,
    platforms: [
      { name: "PC", icon: "assets/img/plattforms/pc.png" },
      { name: "PS4", icon: "assets/img/plattforms/ps4.png" },
      { name: "PS5", icon: "assets/img/plattforms/ps5.png" },
      { name: "Xbox One", icon: "assets/img/plattforms/xboxone.png" },
      { name: "Xbox Series X/S", icon: "assets/img/plattforms/xboxseries.png" },
    ],
    soldCopies: 6000000,
    genre: "Sport",
    rating: 7.2,
    metacritic: 68,
    likes: 1234,
    ageRating: { name: "USK 0", icon: "assets/img/usk/usk-0.png" },
    modes: ["Singleplayer", "Multiplayer", "Online"],
    dlcs: [],
    tags: ["Basketball", "Simulation", "eSports"],
    liked: false,
    description:
      "Die aktuellste Basketballsimulation mit realistischem Gameplay, MyCareer-Modus und Online-Ligen.",
    ownComment: [],
    comments: [
      {
        name: "HoopsFan99",
        comment:
          "Gameplay top, aber die Pay-to-Win-Elemente verderben es etwas.",
        rating: 6,
        date: "2024-01-03",
      },
    ],
    ingamePics: [
      "assets/img/ingame-pics/nba-2k-24/nba2k24-1.png",
      "assets/img/ingame-pics/nba-2k-24/nba2k24-2.png",
      "assets/img/ingame-pics/nba-2k-24/nba2k24-3.png",
      "assets/img/ingame-pics/nba-2k-24/nba2k24-4.png",
      "assets/img/ingame-pics/nba-2k-24/nba2k24-5.png",
      "assets/img/ingame-pics/nba-2k-24/nba2k24-6.png",
    ],
  },
  {
    title: "Apex Legends",
    cover: "assets/img/cover/apex-legends.jpg",
    developer: "Respawn Entertainment",
    releaseYear: 2019,
    price: 0.0,
    platforms: [
      { name: "PC", icon: "assets/img/plattforms/pc.png" },
      { name: "PS4", icon: "assets/img/plattforms/ps4.png" },
      { name: "PS5", icon: "assets/img/plattforms/ps5.png" },
      { name: "Xbox One", icon: "assets/img/plattforms/xboxone.png" },
      { name: "Xbox Series X/S", icon: "assets/img/plattforms/xboxseries.png" },
      { name: "Nintendo Switch", icon: "assets/img/plattforms/switch.png" },
    ],
    soldCopies: 100000000,
    genre: "Battle Royale",
    rating: 8.1,
    metacritic: 89,
    likes: 1234,
    ageRating: { name: "USK 16", icon: "assets/img/usk/usk-16.png" },
    modes: ["Multiplayer", "Online Coop"],
    dlcs: [],
    tags: ["Shooter", "Battle Royale", "eSports", "Team-basiert"],
    liked: true,
    description:
      "Ein rasanter Battle-Royale-Shooter mit einzigartigen Legenden, taktischem Teamplay und neuen Updates jede Saison.",
    ownComment: [],
    comments: [
      {
        name: "LegendHunter",
        comment:
          "Die besten Gunfights in einem BR. Ständiger Support vom Entwicklerteam!",
        rating: 9,
        date: "2023-10-05",
      },
    ],
    ingamePics: [
      "assets/img/ingame-pics/apex-legends/apexlegends-1.png",
      "assets/img/ingame-pics/apex-legends/apexlegends-2.png",
      "assets/img/ingame-pics/apex-legends/apexlegends-3.png",
      "assets/img/ingame-pics/apex-legends/apexlegends-4.png",
      "assets/img/ingame-pics/apex-legends/apexlegends-5.png",
    ],
  },
  {
    title: "Baldur's Gate 3",
    cover: "assets/img/cover/baldurs-gate-3.jpg",
    developer: "Larian Studios",
    releaseYear: 2023,
    price: 59.99,
    platforms: [
      { name: "PC", icon: "assets/img/plattforms/pc.png" },
      { name: "PS5", icon: "assets/img/plattforms/ps5.png" },
      { name: "Xbox Series X/S", icon: "assets/img/plattforms/xboxseries.png" },
    ],
    soldCopies: 10000000,
    genre: "Fantasy RPG",
    rating: 9.7,
    metacritic: 96,
    likes: 1234,
    ageRating: { name: "USK 18", icon: "assets/img/usk/usk-18.png" },
    modes: ["Singleplayer", "Online Coop"],
    dlcs: [],
    tags: ["D&D", "Rundenbasiert", "Entscheidungen", "Koop"],
    liked: true,
    description:
      "Erlebe ein episches Abenteuer in der Welt von Dungeons & Dragons mit intensiven Dialogen und taktischen Kämpfen.",
    ownComment: [],
    comments: [],
    ingamePics: [
      "assets/img/ingame-pics/baldurs-gate-3/baldursgate3-1.png",
      "assets/img/ingame-pics/baldurs-gate-3/baldursgate3-2.png",
      "assets/img/ingame-pics/baldurs-gate-3/baldursgate3-3.png",
      "assets/img/ingame-pics/baldurs-gate-3/baldursgate3-4.png",
    ],
  },
  {
    title: "Mass Effect Legendary Edition",
    cover: "assets/img/cover/mass-effect-legendary.jpg",
    developer: "BioWare",
    releaseYear: 2021,
    price: 29.99,
    platforms: [
      { name: "PC", icon: "assets/img/plattforms/pc.png" },
      { name: "PS4", icon: "assets/img/plattforms/ps4.png" },
      { name: "Xbox One", icon: "assets/img/plattforms/xboxone.png" },
    ],
    soldCopies: 4000000,
    genre: "Sci-Fi RPG",
    rating: 8.8,
    metacritic: 86,
    likes: 1234,
    ageRating: { name: "USK 16", icon: "assets/img/usk/usk-16.png" },
    modes: ["Singleplayer"],
    dlcs: ["Alle Haupt-DLCs der Originaltrilogie"],
    tags: ["Sci-Fi", "Entscheidungen", "Story-driven", "Charaktere"],
    liked: true,
    description:
      "Erlebe die überarbeitete Mass Effect-Trilogie mit optimierter Grafik, Gameplay und allen DLCs in einem Paket.",
    ownComment: [],
    comments: [],
    ingamePics: [
      "assets/img/ingame-pics/mass-effect-legendary-edition/masseffect-1.png",
      "assets/img/ingame-pics/mass-effect-legendary-edition/masseffect-2.png",
      "assets/img/ingame-pics/mass-effect-legendary-edition/masseffect-3.png",
      "assets/img/ingame-pics/mass-effect-legendary-edition/masseffect-4.png",
      "assets/img/ingame-pics/mass-effect-legendary-edition/masseffect-5.png",
    ],
  },
  {
    title: "Mount & Blade II: Bannerlord",
    cover: "assets/img/cover/mount-&-blade-bannerlord.jpg",
    developer: "TaleWorlds",
    releaseYear: 2022,
    price: 39.99,
    platforms: [
      { name: "PC", icon: "assets/img/plattforms/pc.png" },
      { name: "PS4", icon: "assets/img/plattforms/ps4.png" },
      { name: "PS5", icon: "assets/img/plattforms/ps5.png" },
      { name: "Xbox One", icon: "assets/img/plattforms/xboxone.png" },
      { name: "Xbox Series X/S", icon: "assets/img/plattforms/xboxseries.png" },
    ],
    soldCopies: 5000000,
    genre: "Medieval Sandbox",
    rating: 8.3,
    metacritic: 78,
    likes: 1234,
    ageRating: { name: "USK 12", icon: "assets/img/usk/usk-12.png" },
    modes: ["Singleplayer", "Multiplayer"],
    dlcs: [],
    tags: ["Schlachten", "Mittelalter", "Sandbox", "RPG"],
    liked: true,
    description:
      "Der Nachfolger von Warband mit erweiterten Schlachten, Diplomatie, Handel und dynastischem Aufbau.",
    ownComment: [],
    comments: [],
    ingamePics: [
      "assets/img/ingame-pics/mount-&-blade-II/mount&blade2-1.png",
      "assets/img/ingame-pics/mount-&-blade-II/mount&blade2-2.png",
      "assets/img/ingame-pics/mount-&-blade-II/mount&blade2-3.png",
      "assets/img/ingame-pics/mount-&-blade-II/mount&blade2-4.png",
    ],
  },
  {
    title: "BioShock Infinite",
    cover: "assets/img/cover/bioshock-infinite.jpg",
    developer: "Irrational Games",
    releaseYear: 2013,
    price: 9.99,
    platforms: [
      { name: "PC", icon: "assets/img/plattforms/pc.png" },
      { name: "PS3", icon: "assets/img/plattforms/ps4.png" },
      { name: "Xbox 360", icon: "assets/img/plattforms/xboxone.png" },
      { name: "Nintendo Switch", icon: "assets/img/plattforms/switch.png" },
    ],
    soldCopies: 11000000,
    genre: "Shooter",
    rating: 9.0,
    metacritic: 94,
    likes: 1234,
    ageRating: { name: "USK 18", icon: "assets/img/usk/usk-18.png" },
    modes: ["Singleplayer"],
    dlcs: ["Burial at Sea"],
    tags: ["Story", "Zeitreisen", "Shooter", "Steampunk"],
    liked: true,
    description:
      "Ein atmosphärischer Story-Shooter in der schwebenden Stadt Columbia mit intensiven Kämpfen und überraschendem Twist.",
    ownComment: [],
    comments: [],
    ingamePics: [
      "assets/img/ingame-pics/bioshock-infinite/bioshock-1.png",
      "assets/img/ingame-pics/bioshock-infinite/bioshock-2.png",
      "assets/img/ingame-pics/bioshock-infinite/bioshock-3.png",
      "assets/img/ingame-pics/bioshock-infinite/bioshock-4.png",
      "assets/img/ingame-pics/bioshock-infinite/bioshock-5.png",
    ],
  },
  {
    title: "Crash Team Racing (CTR): Nitro-Fueled",
    cover: "assets/img/cover/crash-team-racing.jpg",
    developer: "Beenox",
    releaseYear: 2019,
    price: 34.99,
    platforms: [
      { name: "PS4", icon: "assets/img/plattforms/ps4.png" },
      { name: "Xbox One", icon: "assets/img/plattforms/xboxone.png" },
      { name: "Nintendo Switch", icon: "assets/img/plattforms/switch.png" },
    ],
    soldCopies: 3000000,
    genre: "Rennspiel",
    rating: 8.4,
    metacritic: 83,
    likes: 1234,
    ageRating: { name: "USK 6", icon: "assets/img/usk/usk-6.png" },
    modes: ["Singleplayer", "Multiplayer", "Online"],
    dlcs: [],
    tags: ["Racing", "Arcade", "Remake", "Fun"],
    liked: true,
    description:
      "Der kultige Fun-Racer kehrt zurück – mit neuem Look, Online-Modus und allen originalen Strecken.",
    ownComment: [],
    comments: [],
    ingamePics: [
      "assets/img/ingame-pics/ctr-nitro-fueled/ctr-1.png",
      "assets/img/ingame-pics/ctr-nitro-fueled/ctr-2.png",
      "assets/img/ingame-pics/ctr-nitro-fueled/ctr-3.png",
      "assets/img/ingame-pics/ctr-nitro-fueled/ctr-4.png",
      "assets/img/ingame-pics/ctr-nitro-fueled/ctr-5.png",
    ],
  },
];
